#!/usr/bin/with-contenv bash

version=$(/usr/local/bin/plexdrive --version)
echo "Starting Plexdrive v${version}"

configSubDir="${PLEXDRIVE_CONFIG_DIR}"

if [ -r "${configSubDir}/config/config.json" ] && [ -r "${configSubDir}/config/token.json" ]; then
  exec s6-setuidgid abc \
      /bin/sh -c \
        "/usr/local/bin/plexdrive mount -v 2 -c ${PLEXDRIVE_CONFIG_DIR}/config --cache-file=${PLEXDRIVE_CONFIG_DIR}/cache/cache.bolt ${PLEXDRIVE_OPTS} -o allow_other ${PLEXDRIVE_MOUNT_POINT}"
else
  echo "========================================================"
  echo "|| ERROR: Plexdrive config files (config.json and token.json) not found."
  echo "|| Enter on container terminal:"
  echo "||   docker exec -ti CONTAINER_NAME /bin/sh"
  echo "|| Execute a mount commmand manually:"
  echo "||   /usr/local/bin/plexdrive mount -c \\${PLEXDRIVE_CONFIG_DIR}/config --cache-file=\\${PLEXDRIVE_CONFIG_DIR}/cache/cache.bolt \${PLEXDRIVE_OPTS} -o allow_other \${PLEXDRIVE_MOUNT_POINT}"
  echo "|| Follow the steps, enter the client ID, the client secret, follow the link, paste the token obtained"
  echo "|| After this steps, cancel process with Ctrl+C and tiping exit."
  echo "|| Finally restart/recreate the container."
  echo "========================================================"
  sleep 30
fi
